version: '3.5'

services:

  nginx:
    build: .
    ports:
      - 80:80
    container_name: pycontw-nginx
    restart: always
    hostname: pycontw-nginx
    volumes:
        - /var/www/letsencrypt:/var/www/letsencrypt
    networks:
        - pycontw-net
        - network-2022
        - network-2023

networks:
    pycontw-net:
        external: true
    network-2022:
        external: true
    network-2023:
        external: true
